---
title: "Mood and Feelings Questionnaire Report"
date: today
date-format: "MMMM D, YYYY"
format: 
  pdf:
    include-in-header: title.tex
    geometry: margin=0.75in
execute: 
  echo: false
  message: false
  warning: false
params:
  instrument: ""
  codeword: ""
  data_path: ""
---

```{r}
library(tidyverse)
library(gt)
resp <- read.csv(params$data_path)
```

## Assessment: `r params$instrument`

### **Total score:** `r sum(resp$Score, na.rm = TRUE)`

```{r}
#| fig-height: 3

source('materials/mfqProperties.R')
scorePlot(sum(resp$Score, na.rm = TRUE), gsub("\\s*\\(.*\\)$", "", params$instrument))
```

### Item responses

```{r}
resp |>
  mutate(Response = factor(Response,
    levels = c("0", "1", "2"),
    labels = c("Not True", "Sometimes", "True"))) |>
  select(Item, Response) |>
  gt() |>
  tab_style(
    style = cell_fill(color = "pink"),
    locations = cells_body(
      columns = Response,
      rows = Response == "Sometimes"
    )
  ) |>
  tab_style(
    style = cell_fill(color = "red"),
    locations = cells_body(
      columns = Response,
      rows = Response == "True"
    )
  )
```
